### Generated by rprotoc. DO NOT EDIT!
### <proto file: embed.proto>
# message Person {
#   required string name = 1;
#   required int32 id = 2;
#   optional string email = 3;
#   message PhoneNumber {
#     required string number = 1;
#     optional int32 type = 2;
#   } 
#   optional PhoneNumber phone = 4;
# }
# 

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

class Person < ::Protobuf::Message
  defined_in __FILE__
  required :string, :name, 1
  required :int32, :id, 2
  optional :string, :email, 3
  class PhoneNumber < ::Protobuf::Message
    defined_in __FILE__
    required :string, :number, 1
    optional :int32, :type, 2
  end
  optional :PhoneNumber, :phone, 4
end