### Generated by rprotoc. DO NOT EDIT!
### <proto file: simple.proto>
# message Simple {
#   required string name = 1;
#   required int32 id = 2;
#   optional string email = 3;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

class Simple < ::Protobuf::Message
  defined_in __FILE__
  required :string, :name, 1
  required :int32, :id, 2
  optional :string, :email, 3
end